/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'MarkPerry' at '26/09/13 8:21 PM' with Gradle 1.8
 *
 * @author MarkPerry, @date 26/09/13 8:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;

    }
}
