package mperry;

/**
 * @author Nishi Sherine
 * Date : 15-09-2013
 * 
 * This class represents any exceptions generated by the route calculation.
 * If you find that the parameters provided to the  methods are invalid 
 * then it will throw a new instance of this class.
 * 
 */
@SuppressWarnings("serial")
public class RouteException extends Exception  {
	
	public RouteException(String message) {
		super("RouteException: " + message);
	}
	
}
